### ISSUE TITLE
Using the Sample App as a Template for a Python 3 App

### ISSUE THREAD

**Issue by areiman** [GRIDAPPSD/gridappsd-forum#1]
From Casey:

The problem is encountered when running on Python 3. The utils module in gridappsd imports the dateutil module, which appears to not have a direct analogue in Python 3. A workaround for this is to comment out any code in the sample app that imports or uses the gridappsd utils module, and use a placeholder for the utils calls. The sample app does not use the date processing from the dateutil module, so it’s only environment variables that need to be replaced.

**Comment by poorva1209** [comment]
I tested this out and it works with python 3 with the following steps:
1. clone gridappsd-python repo and cd into it
2. Run pip3 install .

Now try to run your app and it should work.
