### ISSUE TITLE
Simulation Output 

### ISSUE THREAD

**Issue by Lakes-lead** [GRIDAPPSD/gridappsd-forum#106]
Hello, 

After running a simulations on the Gridappsd platform, apart from the GUI interface results/output is their another way to extract the results like to a csv or other file output for analysis. 

Thank you

**Comment by poorva1209** [comment]
This is an old possible obsolete issue. closing it with this comment: 

Yes, you can subscribe to the simulation output and store it in a csv file. Or query timeseries data store for simulation output and store the the response in a csv file. 
Please see documentation here: 

https://gridappsd.readthedocs.io/en/latest/using_gridappsd/index.html#subscribe-to-simulation-output

https://gridappsd.readthedocs.io/en/latest/using_gridappsd/index.html#query-simulation-data
