### ISSUE TITLE
Error contracting http://localhost:8889/bigdata/ (000)

### ISSUE THREAD

**Issue by Mvr013** [GRIDAPPSD/gridappsd-forum#108]
I am trying to run the GRIDAPPS-D platform. 
After Getting blazegraph status I got the following error
I got error Error contracting http://localhost:8889/bigdata/ (000)

Kindly help me to run the platform.
![error_1](https://user-images.githubusercontent.com/66704535/130299695-45e9fbdd-ec38-4c59-bc92-9618a4ccd605.JPG)
![error_2](https://user-images.githubusercontent.com/66704535/130299699-e14a84be-aa59-4008-9756-e5753f207102.JPG)
@poorva1209 @shpoudel

**Comment by AAndersn** [comment]
@Mvr013 Is there possibly another service currently using port 8889?

**Comment by shpoudel** [comment]
I was tagged in the issue, but for some reason, I was not notified. Sorry about that.

@Mvr013 Please re-run the same command. Usually, in the first run, there is an error in blazegraph. Let me know how it goes.

**Comment by AAndersn** [comment]
@Mvr013  Please let me know if you are still having this problem. Otherwise, I will close this ticket.

**Comment by AAndersn** [comment]
Closing for lack of response
