### ISSUE TITLE
Co-simulation Bridge Initialization Failed

### ISSUE THREAD

**Issue by Mvr013** [GRIDAPPSD/gridappsd-forum#109]
Hello,
I hope you all doing well.
After running the platform, I saw error message under status section as Co-Simulation Bridge Initialization Failed.

Initially I gor error for password and leter this error I saw in the platform.

Can any one help me to solve this issue.
![Error](https://user-images.githubusercontent.com/66704535/137172439-6c100a3a-0b62-497c-89b0-5fec3468987d.JPG)
@poorva1209

**Comment by poorva1209** [comment]
This issue was resolved by updating the gridappsd-docker and all the containers. Closing this now.
