### ISSUE TITLE
FRS messages in TimeSeries DB

### ISSUE THREAD

**Issue by MaximeBaudette** [GRIDAPPSD/gridappsd-forum#110]
Issue used to track advancement in implementation and integration of FRS messages into GridApps

**Comment by MaximeBaudette** [comment]
@poorva1209 Could you keep me updated of the current status on that item ?

**Comment by poorva1209** [comment]
@ericstephan  is currently is working on it and should have an updated API to test this week.

**Comment by ericstephan** [comment]
Coding changes are complete and have been pushed to git.  @tonya1 @poorva1209 @craig8 I will create a tagged release tomorrow and send out the versions.

These changes include support for frs message type structures and advanced query interface.

**Comment by ericstephan** [comment]
@poorva1209 @tonya1 Please use v1.4 tags for proven-cluster and proven-client repositories.  Stay tuned for documentation regarding some slight augmentations made to the messages to make them consistent so I could keep the user interface generic.

**Comment by poorva1209** [comment]
@tonya1 Make proven container with that tag and let me know. I will give it a try then.

**Comment by tonya1** [comment]
@poorva1209  Please test with docker pull gridappsd/proven:1.4.
