### ISSUE TITLE
Load updated IEEE13OCHRE in Blazegraph

### ISSUE THREAD

**Issue by AAndersn** [GRIDAPPSD/gridappsd-forum#120]
@tonya1, Please create a new Blazegraph container with an updated version of the IEEEOCHRE model

@vmotakat please email Tonya the new CIM XML and measurements.txt files generated by the CIMHub import script.

**Comment by AAndersn** [comment]
@tonya1 When you have built the container, please share the tag with @MaximeBaudette

**Comment by MaximeBaudette** [comment]
In the meantime, I seem to be having issues launching a OCHRE simulation... 
Let me track that in a separate issue over here https://github.com/GRIDAPPSD/gridappsd-forum/issues/122

**Comment by tonya1** [comment]
@MaximeBaudette The test container has been shared through the collaboration site.  You should be receiving an email with instructions to download.

**Comment by MaximeBaudette** [comment]
Excellent, I just started downloading it !
Thanks !

**Comment by MaximeBaudette** [comment]
@tonya1 
Assuming the new tag is `ieee13_ocher_der` and no longer `fastderms` ?

**Comment by tonya1** [comment]
@MaximeBaudette  you are correct .
