### ISSUE TITLE
Wrong display unit for angles on Gridapps-D web GUI

### ISSUE THREAD

**Issue by MaximeBaudette** [GRIDAPPSD/gridappsd-forum#121]
The display unit on the gridapps-D web GUI are wrong and use the quantity base unit (V, W), should display degrees instead
See screenshot
![Screen Shot 2022-05-11 at 11 47 39](https://user-images.githubusercontent.com/15156063/167923974-997dcc35-a812-484e-a0b5-461b7133d3f5.png)

**Comment by shpoudel** [comment]
@bibiraju To fix this, look for the **check box** in "Component type". If the user checks the angle, then display "Degrees" as Y-label in the plot.

**Comment by bibiraju** [comment]
So for angle measurements, the unit should be degrees like the picture below?

![image](https://user-images.githubusercontent.com/12516333/168154332-dfeb14c0-9d60-406f-b0e4-5ddb502ccb57.png)

**Comment by bibiraju** [comment]
@shpoudel should the unit for Power magnitude be VA?

**Comment by shpoudel** [comment]
It is VA, but let's bring this to a standup call or a working meeting if we need to change this to W or Var with some additional math.
