### ISSUE TITLE
Three phase battery data query using API

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/gridappsd-forum#133]
### Discussed in https://github.com/GRIDAPPSD/gridappsd-forum/discussions/132

<div type='discussions-op-text'>

<sup>Originally posted by **vmotakat** June 22, 2022</sup>

PREFIX r: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX c: <http://iec.ch/TC57/CIM100#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?inverter_mrid ?meas_mrid ?phase
WHERE {
  VALUES ?feeder_mrid {"_8F9EA8EC-1CC5-4ABC-8287-3A6D363DB962"}
  ?s r:type ?type.
  ?s c:IdentifiedObject.mRID ?meas_mrid.
  ?s c:Measurement.PowerSystemResource ?eq.
  ?s c:Measurement.Terminal ?trm.
  ?s c:Measurement.phases ?phsraw.
  {bind(strafter(str(?phsraw),"PhaseCode.") as ?phase)} .
  ?eq c:IdentifiedObject.mRID ?inverter_mrid.
  ?eq r:type c:PowerElectronicsConnection.
  ?eq c:Equipment.EquipmentContainer ?fdr.
  ?fdr c:IdentifiedObject.mRID ?feeder_mrid.
}
ORDER BY ?inverter_mrid

I have used above query in blaze graph. Test feeder having three phase batteries along with three phase PV models. I am getting none under phase section  as shown in the bellow image

 
<img width="797" alt="Screen Shot 2022-06-22 at 3 47 10 PM" src="https://user-images.githubusercontent.com/102381298/175124259-8bc11a93-780a-471d-8f4c-3386c77684e6.png">

Can any one help me to understand meaning for same object MRID and measurement MRID for all phases A, B, C and additional none for 3-phase battery object.
@poorva1209 </div>

**Comment by poorva1209** [comment]
@tonya1 Venkat is working with a new model and it looks like there are multiple measurements with the same id. Can you have a look?

**Comment by AAndersn** [comment]
@poorva1209 - I have already worked with Venkat on the issue this morning.

I did not see any obvious reason. I think this may be a question for @temcdrm , so I asked Venkat to create a ticket.

@vmotakat - Could you please re-run with a slightly different query to print out the measurement name + type and update with another screenshot?

```
# list all measurements - not depending on valid model
PREFIX r: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX c: <http://iec.ch/TC57/CIM100#>
SELECT ?name ?phases ?type ?eqid ?trmid ?measid WHERE {
{ ?s r:type c:Discrete. bind ("Discrete" as ?class)}
  UNION
{ ?s r:type c:Analog. bind ("Analog" as ?class)}
	?s c:IdentifiedObject.name ?name .
	?s c:IdentifiedObject.mRID ?measid .
	?s c:Measurement.PowerSystemResource ?eq .
    ?eq c:IdentifiedObject.mRID ?eqid .
  ?eq r:type c:PowerElectronicsConnection.
	?s c:Measurement.Terminal ?trm .
    ?trm c:IdentifiedObject.mRID ?trmid .
	?s c:Measurement.measurementType ?type .
  {?s c:Measurement.phases ?phsraw.
   bind(strafter(str(?phsraw),"PhaseCode.") as ?phases)}
} ORDER BY ?name ?type ?phases
```

**Comment by poorva1209** [comment]
> 

Thanks for the update @AAndersn. When I talked to@vmotakat we printed out the measurement type and for none phases, it was 'soc'.

**Comment by vmotakat** [comment]
Thank you Poorva and Alex. 

none issue sort outed with the help of Poorva that indicating SOC. 

For me for every object two times indicating in the query result for this feeder only. For other feeders I am getting correct representation.

**Comment by poorva1209** [comment]
@AAndersn I am opening this again so we can figure out why he is getting multiple measurements with same id. @tonya1  can help with that.

**Comment by AAndersn** [comment]
@poorva1209 - I have seen similar behavior with other SPARQL queries, where are multiple duplicate entries in the output. The `GROUP BY` syntax can be used to combine duplicate results. I am not sure if it has anything to do with the insert_measurements script or anything in the platform.

**Comment by poorva1209** [comment]
> @poorva1209 - I have seen similar behavior with other SPARQL queries, where are multiple duplicate entries in the output. The `GROUP BY` syntax can be used to combine duplicate results. I am not sure if it has anything to do with the insert_measurements script or anything in the platform.

I thought the same and asked Venkat to do the same query with SDGE model and see if it shows duplicate outputs too. He is not getting duplicate results there so I am assuming it has to do with how the measurements are being inserted for that model. 

@vmotakat Can you use 'group by' so you don't have to be blocked by this issue.

**Comment by AAndersn** [comment]
@poorva1209 - Yes, @vmotakat was able to use the `GROUP BY` syntax successfully, so I had closed the issue earlier

**Comment by poorva1209** [comment]
aah! ok. Didn't know that. Closing it then.
