### ISSUE TITLE
Make sensor service easily configurable

### ISSUE THREAD

**Issue by blthayer** [GRIDAPPSD/gridappsd-forum#15]
Currently, the only way to configure the [sensor service](https://github.com/GRIDAPPSD/gridappsd-sensor-simulator) for a simulation is to modify the source code.

The sensor service should be configurable on a per-simulation basis. In other words, I should be able to run a simulation with 5-minute average meter reads, and after that simulation completes I should be able to run another with 15-minute average meter reads.

The primary two configuration pathways for app developers/users that I see are:
1. Through the viz.
2. Through the platform API when running a simulation. If a separate API call to starting a simulation needed to be made, that would be acceptable.

@craig8 @poorvasharma @temcdrm

**Comment by poorva1209** [comment]
@craig8 @bibiraju I updated my branch for service config changes: https://github.com/poorva1209/GOSS-GridAPPS-D/tree/update_service_config

Please test it with following request: 
`{"power_system_config":{"SubGeographicalRegion_name":"_ABEB635F-729D-24BF-B8A4-E2EF268D8B9E","GeographicalRegion_name":"_73C512BD-7249-4F50-50DA-D93849B89C43","Line_name":"_49AD8E07-3BF9-A4E2-CB8F-C3722F837B62"},"simulation_config":{"power_flow_solver_method":"NR","duration":120,"simulation_name":"ieee13nodeckt","simulator":"GridLAB-D","start_time":1568227747,"run_realtime":true,"simulation_output":{},"model_creation_config":{"load_scaling_factor":1.0,"triplex":"y","encoding":"u","system_frequency":60,"voltage_multiplier":1.0,"power_unit_conversion":1.0,"unique_names":"y","schedule_name":"ieeezipload","z_fraction":0.0,"i_fraction":1.0,"p_fraction":0.0,"randomize_zipload_fractions":false,"use_houses":false},"simulation_broker_port":55488,"simulation_broker_location":"127.0.0.1"},"application_config":{"applications":[{"name":"sample_app","config_string":""}]},"service_configs":[{"id":"gridappsd-sensor-simulator","user_options":{"sensors-config":{"_001cc221-d6e6-485d-bdcc-b84cb643d1ec":{"nominal-voltage":100,"perunit-confidence":0.01,"aggregation-interval":30,"perunit-dropping":0.01},"_00313f7c-5140-47cf-b750-0146bb3d9024":{}},"default_value-perunit-configidence-rate":0.01,"default_value-aggregation-interval":30,"default_value-drop-rate":30,"passthrough-if-not-specified":true}}],"test_config":{"events":[],"appId":"sample_app"}}
`

This is the command by which it starts sensor service: 
`python /gridappsd/services/gridappsd-sensor-simulator/sensor_simulator.py 1776292002 {default_value-drop-rate=30.0, sensors-config={_001cc221-d6e6-485d-bdcc-b84cb643d1ec={nominal-voltage=100.0, perunit-confidence=0.01, aggregation-interval=30.0, perunit-dropping=0.01}, _00313f7c-5140-47cf-b750-0146bb3d9024={}}, default_value-aggregation-interval=30.0, default_value-perunit-configidence-rate=0.01, passthrough-if-not-specified=true}
`

I updated sensor_simulator.config to this: 
```
{
    "id":"gridappsd-sensor-simulator",
    "description":"GridAPPS-D Sensor Simulation Application",
    "creator":"PNNL",
    "inputs":[],
    "outputs":[],
    "static_args": ["(simulationId)"],
    "user_input": {
        "sensors-config": {
            "help": "Enter dictionary of mrid to configuration mapping for the sensors",
            "help_example": {
                    "_001cc221-d6e6-485d-bdcc-b84cb643d1ec": {
                                                "nominal-voltage": 100,
                                                "perunit-confidence": 0.01,
                                                "aggregation-interval": 30,
                                                "perunit-dropping": 0.01
                    },
                    "_00313f7c-5140-47cf-b750-0146bb3d9024":{},
                    "_00313f7c-5140-47cf-b750-0146bb3d9024":{
                                                "nominal-voltage": 35
                    }
             },
            "type": "object",
            "default_value": {}
        },
        "default_value-perunit-configidence-rate": {
            "help": "Set the default_value confidence rate of the equipment",
            "help_example": 0.01,
            "type": "float",
            "max_value": 0.1,
            "min_value": 0.0,
            "default_value": 0.01
        },
        "default_value-aggregation-interval": {
            "help": "Aggregation period in seconds",
            "help_example": 0.01,
            "type": "float",
            "default_value": 30
        },
        "default_value-drop-rate": {
            "help": "Aggregation period in seconds",
            "help_example": 0.01,
            "default_value": 30,
            "type": "float"
        },
        "passthrough-if-not-specified": {
            "help": "Set to true to have measurements pass through if they aren't specified in sensor-config",
            "help_example": true,
            "default_value": true,
            "type": "bool"
        }
    },
    "type":"PYTHON",
    "execution_path": "/gridappsd/services/gridappsd-sensor-simulator/sensor_simulator.py",
    "launch_on_startup":true,
    "multiple_instances":true,
    "environmentVariables":[]
}

```
