### ISSUE TITLE
Having problem running the sample app in IEEE 8500  new model

### ISSUE THREAD

**Issue by shpoudel** [GRIDAPPSD/gridappsd-forum#2]
I am having issues running the sample_app for IEEE 8500 new model. I think my issue lies after calling function "gapps.subscribe(listening_to_topic, toggler)". I couldn't quite follow how the instance of GridAPPSD (gapps) is used for subscribing and how it reaches on_message function.

**Comment by poorva1209** [comment]
The new 8500 model not yet ready for full simulation run. It will be available with release next week. Can you try your code with old 8500 model and see if you recieve simulation output.

**Comment by shpoudel** [comment]
Yes, with old 8500 model, I can receive simulation output.

**Comment by poorva1209** [comment]
Please test the new 9500 model in v2019.07.0 and develop tag. Closing this issue.
