### ISSUE TITLE
Fault in 9500 node model

### ISSUE THREAD

**Issue by shpoudel** [GRIDAPPSD/gridappsd-forum#32]
@poorva1209 and @afisher1 , I worked with 9500 node model to test if faults are working. However, I have an error showing up in the console before I could verify it. I have attached the error as a picture here. Could you please let me know the reasons for such an error?

![image](https://user-images.githubusercontent.com/35777492/66346803-c921f700-e907-11e9-8a9e-3c05bdf340f0.png)

Note: I added a fault to happen 60 seconds after the simulation has started

**Comment by poorva1209** [comment]
@shpoudel : Can you run the simulation multiple times and get the same error every time? This is something the FNCS do randomly so it shouldn't repeat with every simulation.

**Comment by shpoudel** [comment]
@poorva1209 : I ran the simulation couple of times and it was not a success. However, again I encountered a new type of error in the console. Could you please look into it?

![image](https://user-images.githubusercontent.com/35777492/66357509-0b593180-e924-11e9-8508-8e7b51be2895.png)

**Comment by poorva1209** [comment]
@afisher1 Can you check the new error message.

**Comment by poorva1209** [comment]
This is a random thrown by FNCS co-Simulator, not by GridAPPS-D platform. This would be irrelevant once we move to HELICS in March/April release. Closing this issue.
