### ISSUE TITLE
Simulation output not updated

### ISSUE THREAD

**Issue by shpoudel** [GRIDAPPSD/gridappsd-forum#37]
@poorva1209 : I am subscribing to simulation output to check the switch status every time I get a message from the platform. Even if I changed the status of some switch manually, the output remains the same. It was working fine when I gave the demo a few weeks back on the IEEE 123-node system. Is there something I should be aware of? 

Note: I am checking the status of LoadBreakSwitch.

**Comment by poorva1209** [comment]
What release version are you using ?

**Comment by shpoudel** [comment]
I am using 2019.09.1

**Comment by poorva1209** [comment]
Can you also send met the message you are sending to change the switch status,.

**Comment by shpoudel** [comment]
I am changing it from visualization. However, I also tried it by sending the following code. It is just a sample code for opening Switch5 in IEEE 123 node. I get a message in console that the message is passed but I don't see the corresponding change in simulation output back. 

 op = ['_F2599E92-5611-4112-B522-3D3044A8055F']
        if self.flag_sw == 0:
            for sw_mrid in op:
                self._open_diff.add_difference(sw_mrid, "Switch.open", 1, 0)
                msg = self._open_diff.get_message()
                print (msg)
                self._gapps.send(self._publish_to_topic, json.dumps(msg))  
                self.flag_sw = 1

**Comment by shpoudel** [comment]
Following are the snapshots:
![image](https://user-images.githubusercontent.com/35777492/67229738-c556a000-f3f0-11e9-9dcf-8a355de5b370.png)
![image](https://user-images.githubusercontent.com/35777492/67229774-d7d0d980-f3f0-11e9-903c-2b6dc91b2255.png)

**Comment by poorva1209** [comment]
v2019.10.0 has been updated to resolve this issue. Please test it again by stopping and pulling the containers again.
