### ISSUE TITLE
Switch open command not working, switch measurements possibly reporting the wrong state

### ISSUE THREAD

**Issue by blthayer** [GRIDAPPSD/gridappsd-forum#43]
@poorva1209 @Jeffrey-Simpson @craig8 @shpoudel @temcdrm 

## Background information
Platform version: `v2019.10.0`
Model: 9500, mrid: `_AAE94E4A-2465-6F5E-37B1-3E72183A4E44`

As the title infers, this is a little bit of a "double issue" but both aspects are tightly coupled.

Switch CIM name: `ln0895780_sw`
Switch name in GridLAB-D model: `"swt_ln0895780_sw"`
Switch MRID: `_1B6A5DFD-9ADA-404A-83DF-C9AC89D9323C`
Switch state measurement MRIDs:
- `_41a7539c-7f97-492e-bc53-bfe0859dfeaf`
- `_ba7b8fd8-0bc5-41eb-a01a-90272549004d`
- `_47fdb278-d63c-4947-a5bb-42dbb23be94a`

Note that I used my code to obtain the MRIDs, and I confirmed that they match what's in the platform's `model_dict.json` file which gets generated to start a simulation. However, it would probably be valuable for a third party to verify that my switch name, switch MRID, and state measurement MRIDs are correct and consistent.

## Switch measurements possibly reporting incorrect state
When I run the simulation and listen to the measurements corresponding to the switch states, all the values come back as `1` (which should correspond to "open," right?). However, taking a look at the base model, this switch should be closed. Here's the relevant snippet:
```
object switch { // CIM LoadBreakSwitch
  name "swt_ln0895780_sw";
  from "n1140519";
  to "d5895780-3_int";
  phases ABC;
  status CLOSED;
  continuous_rating_A 400.00;
  continuous_rating_B 400.00;
  continuous_rating_C 400.00;
  emergency_rating_A 600.00;
  emergency_rating_B 600.00;
  emergency_rating_C 600.00;
}
```
If you take a look at the [fncs_goss_bridge](https://github.com/GRIDAPPSD/GOSS-GridAPPS-D/blob/releases/2019.10.0/services/fncsgossbridge/service/fncs_goss_bridge.py) (do a search for "Switch.open" and go to the second result) you'll find the following snippet:
```python
                    elif cim_attribute == "Switch.open":
                        if int(x.get("value")) == 1:
                            val = "OPEN"
                        else:
                            val = "CLOSED"
```
This leads me to believe that a measurement of `1` for position indicates the switch should be open. However, note that this is the opposite behavior as capacitors, which is quite confusing. Here's the capacitor snippet from the fncs_goss_bridge:
```python
                    elif cim_attribute == "ShuntCompensator.sections":
                        if int(x.get("value")) == 1:
                            val = "CLOSED"
                        else:
                            val = "OPEN"
```
**EDIT**
I was looking further into the fncs_goss_bridge code and found the following snippets in the `_get_fncs_bus_messages` function:
```python
                                    if conducting_equipment_type == "LinearShuntCompensator":
                                        if property_name in ["shunt_"+phases,"voltage_"+phases]:
                                            val = complex(val_str)
                                            (mag,ang_rad) = cmath.polar(val)
                                            ang_deg = math.degrees(ang_rad)
                                            measurement["magnitude"] = mag
                                            measurement["angle"] = ang_deg
                                        else:
                                            if val_str == "OPEN":
                                                measurement["value"] = 0
                                            else:
                                                measurement["value"] = 1
```
```python
                                    elif conducting_equipment_type in ["LoadBreakSwitch", "Recloser", "Breaker"]:
                                        if property_name in ["power_in_"+phases,"voltage_"+phases,"current_in_"+phases]:
                                            val = complex(val_str)
                                            (mag,ang_rad) = cmath.polar(val)
                                            ang_deg = math.degrees(ang_rad)
                                            measurement["magnitude"] = mag
                                            measurement["angle"] = ang_deg
                                        else:
                                            if val_str == "OPEN":
                                                measurement["value"] = 0
                                            else:
                                                measurement["value"] = 1
```
Notice these snippets infer that `1` corresponds to "OPEN" and `0` corresponds to "CLOSED." This seems to be a contradiction and a bug.

**END EDIT**
The [GridAPPS-D documentation](https://gridappsd.readthedocs.io/en/latest/developer_resources/index.html#cim-documentation) does not specify whether a measurement value of `1` corresponds to open or closed. **Updating the documentation to make it explicitly clear how position measurements are mapped to open/closed is one important desired outcome of this ticket.** It's possible I'm just missing it, and if that's the case I would appreciate being pointed in the right direction.

## Switch command does not change state measurement values
Setting aside whether or not `1` corresponds to open or closed, I still am unable to send in a command that actually changes the state. I've tried this through the viz (adding a scheduled event), through application code that starts a simulation (again, via a scheduled event), and finally through application code sending a command into the running simulation. 

This behavior is most easily reproduced by sending a command into the running simulation. For convenience, I've reproduced the command below (note to use it you'll need to update `simulation_id` and possibly `timestamp`):
```
{
  "command": "update",
  "input": {
    "simulation_id": "1768473424",
    "message": {
      "timestamp": 1572456539,
      "difference_mrid": "dc9a0b37-09bb-453d-8677-21442690acb6",
      "reverse_differences": [
        {
          "object": "_1B6A5DFD-9ADA-404A-83DF-C9AC89D9323C",
          "attribute": "Switch.open",
          "value": 1
        }
      ],
      "forward_differences": [
        {
          "object": "_1B6A5DFD-9ADA-404A-83DF-C9AC89D9323C",
          "attribute": "Switch.open",
          "value": 0
        }
      ]
    }
  }
}
```
I've sent this command in both of the following ways:
- reverse_difference value = 1, forward_difference value =0
- reverse_difference value = 0, forward_difference value = 1

The switch does not appear to change state in either case. Here are the basic steps to reproduce:
1. Start simulation
2. Subscribe to simulation output, filter to obtain only the measurements associated with the three state measurement MRIDs provided in the background section. You'll notice that the `value` for all three measurements comes back as `1`.
3. Send in the command listed above.
4. Notice that the values coming out are still all `1`.
5. Swap the forward/reverse difference values (i.e. change 0 to 1 and 1 to 0 in the command listed above)
6. Send in modified command.
7. Notice the values coming out are still all `1`.

**Comment by shpoudel** [comment]
@blthayer: I agree with you on the second part of your title: switch measurements possibly reporting the wrong state and it's similar to what I mentioned in this issue (https://github.com/GRIDAPPSD/gridappsd-forum/issues/37). 

What I observed back then was: When I changed the switch status for restoration, then the change in binary value, Pos (0/1) is not reflected in the simulation output. However, the switch current changes between some value to 0 (I looked into simulation output with type = "A") while toggling the switch. 

For me, the open command was working in v2019.09.1 but I haven't checked it for the new version yet.

From my understanding "measurment mrid" for switch position (Pos) in simulation output will give 0 for an open switch and 1 for a closed switch. But when sending command, "Switch.open" attribute with forward_value as 1 means open the switch. I know this is confusing and I have been following this logic so far.

**Comment by temcdrm** [comment]
There is a semantic difference between CIM's Switch.open attribute, which is a Boolean, and the switch position, which is an enumeration. We've been using the GridLAB-D convention where Pos=0 means open, and Pos=1 means closed.  I'm attaching a screen shot from the Web showing a different four-state Pos enumeration from IEC 61850.  Shiva's last paragraph describes the way to handle this; even if we later adopt the four-state convention, this will not match CIM's Switch.open.

I think this has tripped up others in the CIM community before.
<img width="909" alt="Screen Shot 2019-10-30 at 12 57 56 PM" src="https://user-images.githubusercontent.com/8473679/67894361-97bad680-fb15-11e9-9735-d194c7676da7.png">

**Comment by poorva1209** [comment]
Yeah, I can reproduce the issue. I am currently testing it with updated fncs goss bridge and Viz app. I will let you know how that goes.

**Comment by poorva1209** [comment]
@shpoudel @temcdrm 

Just to be clear,
For switch Pos measurements: 1 is closed and 0 is open.
For Switch.open command: 1 is open and 0 to closed.

Do I understand it correctly?

**Comment by temcdrm** [comment]
Yes, that’s the intent.

**Comment by shpoudel** [comment]
The first statement is correct. For the second statement, 1 is to open if forward_value is 1. @poorva1209 if you are working with this one, could you also please also check if "Pos" gets updated if you change the switch status manually or via code. This will also answer my issue (https://github.com/GRIDAPPSD/gridappsd-forum/issues/37)

**Comment by poorva1209** [comment]
@shpoudel Yes #37 and this issue basically the same. I thought there is a bug in fncsgossbridge and Viz app with the open/close values. But seems like they are both doing it right. This means the values are not changing in GridLAB-D. Let me capture the exact command fncsbridge is sending to gridlab-d and maybe Frank can help with this. 
@temcdrm Just to be sure, does anything changed in model with regard to switches in the last few weeks that would not allow the simulation to change its status?

**Comment by blthayer** [comment]
Thanks @temcdrm and @shpoudel for the pointers. I'll update my code to handle the differences between the measurement state and the switch command.

**Comment by shpoudel** [comment]
@poorva1209: One comment on your question to Tom. This was working fine when I gave a demo for the IEEE 123-node (9/19/2019).

**Comment by temcdrm** [comment]
@poorva1209 There have been no model changes that would affect this issue.

**Comment by poorva1209** [comment]
v2019.10.0 has been updated to resolve this issue. Please test it again by stopping and pulling the containers again.

**Comment by blthayer** [comment]
@poorva1209 - what's changed in the container? I need this information so I can decide whether I need to update all my testing files or not (which I already did for the 2019.10.0 release...)

**Comment by poorva1209** [comment]
The simulation output is now correctly publishing switch open/close state.

**Comment by blthayer** [comment]
@poorva1209 - I can confirm the switch commands are now working in `v2019.10.0`
