### ISSUE TITLE
Time out error

### ISSUE THREAD

**Issue by therahuljha** [GRIDAPPSD/gridappsd-forum#47]
@poorva1209 I am facing time out error whenever I try to query the regulator and capacitor mrids for 9500 node. I am running in develop  version. 

 raise TimeoutError("Request not responded to in a timely manner!")
gridappsd.goss.TimeoutError: Request not responded to in a timely manner!

**Comment by therahuljha** [comment]
I tried by changing time out to 180. But, still I am getting TimeoutError.

**Comment by poorva1209** [comment]
@therahuljha Please add the query request to the comment.

**Comment by therahuljha** [comment]
topic = "goss.gridappsd.process.request.data.powergridmodel"
    message = {
        "modelId": model_mrid,
        "requestType": "QUERY_OBJECT_MEASUREMENTS",
        "resultFormat": "JSON",
        "objectType": "PowerTransformer"}     
    obj_msr_reg = gapps.get_response(topic, message, timeout=180)
 
    message = {
        "modelId": model_mrid,
        "requestType": "QUERY_OBJECT_MEASUREMENTS",
        "resultFormat": "JSON",
        "objectType": "LinearShuntCompensator"}     
    obj_msr_cap = gapps.get_response(topic, message, timeout=180)
 
    message = {
        "modelId": model_mrid,
        "requestType": "QUERY_OBJECT_MEASUREMENTS",
        "resultFormat": "JSON",
        "objectType": "EnergyConsumer"}     
    obj_msr_loads = gapps.get_response(topic, message, timeout=180)
    regulators = get_regulators_mrids(gapps, model_mrid)  
    capacitors = get_capacitors_mrids(gapps, model_mrid)

**Comment by poorva1209** [comment]
Thanks, I will try it now.

**Comment by poorva1209** [comment]
@therahuljha Try starting your application once the simulation has started running.

**Comment by therahuljha** [comment]
Yes, I tried that. It is working fine with version 2019.10.0

**Comment by poorva1209** [comment]
ok. thanks. Closing this issue.
