### ISSUE TITLE
Unbalanced rooftop PV

### ISSUE THREAD

**Issue by AAndersn** [GRIDAPPSD/gridappsd-forum#53]
This is a model error that Tom caught last week. The rooftop PV as generated by WSU had different capacities on the 120V .1 and .2 phases of each customer. While not a severe problem, it is unrealistic.

I have corrected the original DSS files, which need to be reimported into Blazegraph.

[Corrected PV.zip](https://github.com/GRIDAPPSD/gridappsd-forum/files/3860284/Corrected.PV.zip)

**Comment by shpoudel** [comment]
@AAndersn @poorva1209: 

I already fixed this issue, created the pull request and it's merged already. I think Alexander missed the conversation in gridappsd-forum (#48) where I talked about the modification I made. However, I followed different definition than yours and you can see it here:
https://github.com/GRIDAPPSD/Powergrid-Models/tree/develop/blazegraph/test/dss/WSU. 

Please let me know if you want it to be done based on the zip file you provided.
