### ISSUE TITLE
An error in gridappsd-docker terminal

### ISSUE THREAD

**Issue by shpoudel** [GRIDAPPSD/gridappsd-forum#56]
@poorva1209: I am getting the following error so frequently while starting the gridappsd container (after doing ./run.sh -t develop).

![image](https://user-images.githubusercontent.com/35777492/69577728-fa7c8200-0f9c-11ea-81cf-cb1ee0e35bf0.png)

Also tagging @blthayer and @Jeffrey-Simpson if you have also experienced such error.

**Comment by shpoudel** [comment]
FYI: The error comes up once I start the platform and it starts printing message in **simulation status** console

**Comment by blthayer** [comment]
I'm not personally seeing this error on develop.

**Comment by AAndersn** [comment]
Closing stale issue. These errors no longer appear in ~develop
