### ISSUE TITLE
Update Alarm UI

### ISSUE THREAD

**Issue by Jon8080** [GRIDAPPSD/gridappsd-forum#59]
Alarm UI should be updated to replace MRID with timestamp for the alarm initiation.

**Comment by poorva1209** [comment]
@Jon8080 Just confirming - do we still need this change in UI ?

**Comment by Jon8080** [comment]
Yes.

**Comment by poorva1209** [comment]
We added the timestamp to the alarm service output and UI. Closing this issue.
