### ISSUE TITLE
GridAPPS-D develop branch non-critical simulation startup bugs

### ISSUE THREAD

**Issue by ArunWSU** [GRIDAPPSD/gridappsd-forum#61]
Dear Ms. Poorva, 
 I'm just reporting the non-critical bugs that I sent in email last Thursday.  Currently, I'm working on the _develop_ branch of the gridappsd-docker. These bugs are ever more frequent recently for my instance, as I start or re-run the simulation. For most of the instances presented below, stopping and restarting containers is the fix I'm adopting. The bugs are
1. FNCS initialization error
![Dec 4 FNCS initialize error.png](https://images.zenhubusercontent.com/5d1bf0f68871121fe293f312/9e4bfb73-aeec-48ac-ab51-d93d4031faf4)
2. Username null error
![Dec 4 user name null error.png](https://images.zenhubusercontent.com/5d1bf0f68871121fe293f312/31891b6d-ab95-4a24-980a-37fd14910549)
3. No load schedule error. Reported in Bug #45. Specifically, this error occurs when the simulation time step is small, which is less than 50 seconds, and not in other cases, in my instance.
![Dec 5 No load schedule data.png](https://images.zenhubusercontent.com/5d1bf0f68871121fe293f312/f333f088-cce0-45f1-a568-e2f284387fdc)
4. Poll time_out error. 
![Dec 10 Poll time_out](https://user-images.githubusercontent.com/37948729/70579726-541ca900-1b66-11ea-850b-db44e21d27b5.png)

Sincere Regards,
Arun.

**Comment by AAndersn** [comment]
Closing stale issue. FNCS has been replaced by HELICS as the default bridge and these errors no longer appear
