### ISSUE TITLE
fncs fatal error when starting simulation

### ISSUE THREAD

**Issue by AAndersn** [GRIDAPPSD/gridappsd-forum#62]
Today, we have ran into a new error on both the EIOC pyvvo and my local machine. When starting a simulation, the fncs bridge runs into a fatal error:
 
![fncs fatal error](https://user-images.githubusercontent.com/19935503/70575588-a60c0180-1b5b-11ea-8184-4c33df6af7cc.png)

On some simulation runs the simulation log stops there. On others, the simulation continues running, but no data is passed to the viz.

**Comment by poorva1209** [comment]
@craig8 I see you merged changes in fncs goss bridge - Can that do this ?

**Comment by AAndersn** [comment]
Update: Today the error is not present on new simulation runs. However, if the simulation is stopped using the square stop button and then restarted, the fncs goss brdige still encounters the fatal error:

![image](https://user-images.githubusercontent.com/19935503/70662349-e67e8480-1c1a-11ea-8829-b05e7e4ff736.png)


Log message:

```

2019-12-11 21:27:22,449 Thread-203 ERROR [gov.pnnl.goss.gridappsd.log.LogManagerImpl] - 1576099642448|SimulationProcess|1105872583|ERROR|system|ERROR
FNCS Initialization Failed

2019-12-11 21:27:22,449 Thread-46 ERROR [gov.pnnl.goss.gridappsd.log.LogManagerImpl] - 1576099642448|SimulationProcess|1105872583|ERROR|system|ERROR
FNCS Initialization Failed
```

**Comment by AAndersn** [comment]
Latest develop tag no longer has this problem. Simulations can be stopped, paused, restarted with no errors.

Is this due to switch to HELICS or was this bug fixed?

**Comment by poorva1209** [comment]
This was due to some changes in the GridLAB-D latest release. This has been resolved. You can close this issue.
