### ISSUE TITLE
Enhancement: Rescaling of voltage stripcharts

### ISSUE THREAD

**Issue by AAndersn** [GRIDAPPSD/gridappsd-forum#63]
@poorva1209 This would be really nice to have in the final Monday release, but not critical for the eval.

Currently, the stripcharts scale from zero to the value, which is sometimes very hard to read for voltage values since the acceptable range is 0.95 to 1.05 pu. It would be easier to read the values if the y-axis was scaled to +-- 10% of the nominal value. 

Example: voltage plot is 7138V, so then the y-axis would scale from 6400 to 7800 instead of zero to 7800 as in current release.

**Comment by poorva1209** [comment]
@nhuyvan Is this doable by Monday ?

**Comment by nhuyvan** [comment]
@poorva1209 This is an easy change
