### ISSUE TITLE
Voltage violation in 9500 node system 

### ISSUE THREAD

**Issue by therahuljha** [GRIDAPPSD/gridappsd-forum#64]
@poorva1209  I am observing total voltage violations = 191 whenever I start the platform. This can be seen in the picture attached below.  
![voltagevoilation1](https://user-images.githubusercontent.com/54757484/75490473-20813c00-5969-11ea-852c-22fa9bf06c00.PNG)

Further,  by setting the same control setting obtained from the platform in OpenDSS (offline), there are no voltage violations.

**Comment by AAndersn** [comment]
The GridLab-D simulation uses a different load ZIP file than the OpenDSS model. Also, the output of PV resources is based on the weather file. Running the simulation on different days of the year and different times of day will result in varying number of voltage violations, which will again be different from those in OpenDSS.
