### ISSUE TITLE
Issue with 123PV

### ISSUE THREAD

**Issue by therahuljha** [GRIDAPPSD/gridappsd-forum#71]
@poorva1209 For the IEEE123pv system, I am trying to send the Q control to the PV system. The Q value for the PVs are very high value,  for example - PVsystem.DG_72 has Q= 279 kVAr   . 
However I am not observing any changes in the system, like change in  voltage or power flow. 

This is the message which I am passing
 self._pv_qpower.add_difference(qpv_mrid['mrid'], "PowerElectronicsConnection.q", qpv_mrid['val'], 0)                                        
                msg = self._pv_qpower.get_message()
                self._gapps.send(self._publish_to_topic, json.dumps(msg))
                self._pv_qpower.clear()

This is the message which I am receiving from platform
![image](https://user-images.githubusercontent.com/54757484/88958799-cfe27780-d255-11ea-988b-0cf2c87bbff7.png)

Please let me know if I am sending correct message.

@Jeffrey-Simpson If I remember correctly, you worked on this system, please let me know if there is something wrong.

**Comment by poorva1209** [comment]
Obsolete Issue. Closing.
