### ISSUE TITLE
Controllability of single-phase PV

### ISSUE THREAD

**Issue by cmmooari** [GRIDAPPSD/gridappsd-forum#77]
Dear Gridapps-D developers,

It is noticed PV systems are grouped by bus in the message returned from the query function, although those PV systems are defined as single-phase devices in the dss file. Such that, the output powers of PVs connected to the same bus yet different phases are forced to be balanced, and we loss the flexibility to control the PV injection on different phase separately.   

Just wondering, is there a way to overwrite this setting and enable the independent control of PVs on different phases?

Thank you very much.

**Comment by afisher1** [comment]
The only way to do this currently would be to split up the PV system into three separate PVs in the model (one per phase). Then you would have the ability to control the power output of the PVs by phase.
