### ISSUE TITLE
Errors in Timeserisa API documentation

### ISSUE THREAD

**Issue by blthayer** [GRIDAPPSD/gridappsd-forum#8]
[Link to documentation](https://gridappsd.readthedocs.io/en/latest/using_gridappsd/index.html#timeseries-api)

1. The documentation specifies the data type of data/query filters (e.g. string or number), but as far as I can tell, all data comes back as a string. JSON supports numbers, so it's a little silly that they're being cast to a string just so that the user can cast them back to numbers in their application.
2. For [simulation data](https://gridappsd.readthedocs.io/en/latest/using_gridappsd/index.html#query-simulation-data) the documentation notes that `value [number]` is only a valid filter for the `Input Message type`. While I haven't checked trying to use `value` as a filter, it certainly comes back as a field when querying for output data (i.e. if `hasSimulationMessageType = 'OUTPUT'`). So `value [number]` may belong in the `Both input and output message type` area. 
3. While not an error, it sure would be nice if all the possible data columns for simulation data were documented. For `OUTPUT` messages, I've seen the following:
`['hasSimulationMessageType', 'measurement_mrid', 'angle', 'magnitude', 'simulation_id', 'value', 'time']`

**Comment by poorva1209** [comment]
> The documentation specifies the data type of data/query filters (e.g. string or number), but as far as I can tell, all data comes back as a string. JSON supports numbers, so it's a little silly that they're being cast to a string just so that the user can cast them back to numbers in their application.

API and documentation updated.

> For simulation data the documentation notes that value [number] is only a valid filter for the Input Message type. While I haven't checked trying to use value as a filter, it certainly comes back as a field when querying for output data (i.e. if hasSimulationMessageType = 'OUTPUT'). So value [number] may belong in the Both input and output message type area.

@ericstephan @bibiraju Add value as a query filter for the simulation output message. 

> While not an error, it sure would be nice if all the possible data columns for simulation data were documented. For OUTPUT messages, I've seen the following:
['hasSimulationMessageType', 'measurement_mrid', 'angle', 'magnitude', 'simulation_id', 'value', 'time']

Documentation updated.
