### ISSUE TITLE
Query Historical Sensor Service Data

### ISSUE THREAD

**Issue by shpoudel** [GRIDAPPSD/gridappsd-forum#80]
@poorva1209 @craig8 : I was trying to use the sensor service data made available through gridappsd/influxdb:historical. It pulls 29.99 GB of an image (./run.sh) and while extracting it throws an error saying **no space left**. I see my system has a total of around 51GB space available. Any thoughts on this? Do the ~30GB data have all the simulation output saved for a week?

Also, I have a question regarding the pre-populated historical data generated from sensor service. When you run the simulation and store the historical data, can we select some object types and save the measurements associated with only those object types? I am asking this because, for any application, the entire simulation output might not be of use and if we want to store the entire simulation output for 2-3 weeks, we might always have a memory constraint.

![image](https://user-images.githubusercontent.com/35777492/95228047-b577cd80-07b3-11eb-93f9-2d80cd14616a.png)

**Comment by shpoudel** [comment]
@poorva1209 @craig8 

I am following up on the same issue here. I pulled the updated image (gridappsd/influxdb:historical_1day). I used the following request with some filters. I am attaching a part of the response as well (first three dictionaries). I am expecting this: For one time step, there should be two measurements as I have two different mrids in the filter. But, we don't see such a pattern in the image. The alternative timestamp makes a 15 min time interval (1373551484 - 1373552384 = 900). Am I missing something here?

{'queryMeasurement': 'gridappsd-sensor-simulator', 
'queryFilter': {'simulation_id': '1905271421', 'starttime': '1373551205', 'endtime': '13736655590', 'measurement_mrid': ['_3fe87015-7e58-4271-ae78-523dc47b47ad', '_20f07f38-1160-4ca8-be34-f237d4f37b1b']}, 
'responseFormat': 'JSON'}

![image](https://user-images.githubusercontent.com/35777492/96046674-b39fb100-0e28-11eb-82d0-d6de94958022.png)

**Comment by poorva1209** [comment]
Sensor service introduces missing data to inject realism so that could be one reason. But let me check influxdb directly for these mrids and timestamps and I will get back to you.

**Comment by poorva1209** [comment]
@shpoudel Is this issue resolved in new historical data since we are not using randomization anymore.

**Comment by shpoudel** [comment]
This can be closed. However, I have another related issue opened on the board.

https://github.com/GRIDAPPSD/GOSS-GridAPPS-D/issues/1390
