### ISSUE TITLE
Timeseries Influx DB not recording simulation input from Test Manager

### ISSUE THREAD

**Issue by AAndersn** [GRIDAPPSD/gridappsd-forum#84]
When running a simulation, the Influx DB is only recording simulation input for switching actions if they come from the Viz or another application. 

If the switch event comes from the simulation config file or uploaded through the Test Manager, nothing is recorded. 

Running the following Timeseries API query to get the simulation input commands:
```
{
    "queryMeasurement": "simulation",
    "queryFilter": {
        "simulation_id": viz_simulation_id,
        "hasSimulationMessageType": "INPUT"},
    "responseFormat": "JSON"
}
```

Currently using the test_config setup from https://github.com/GRIDAPPSD/gridappsd-hackathon/blob/main/Run123NodeDemo.py. Also have tried copying the difference message into an event JSON. 

The switch event is being processed correctly by the platform and shows up in both the alarms and in the viz. However, it is not showing up in the Influx DB.

**Comment by poorva1209** [comment]
@ericstephan Proven/Influxdb is not storing simulation input if the 'value' is a float. It works when the value is an integer. We need to change Proven side to make sure simulation input is stored for float values too. Sample simulation input is here: https://gridappsd.readthedocs.io/en/latest/using_gridappsd/index.html#send-input-to-simulation. Change the value to 1.0 and 0.0 to test this. 

Let me know when you make an update to proven and I can test this for you. Meanwhile, I am assigning this task to you.
