### ISSUE TITLE
Installation on Windows 

### ISSUE THREAD

**Issue by Lakes-lead** [GRIDAPPSD/gridappsd-forum#85]
Hello is there a guide on how to install GridAppsD in windows ?

Thank you

**Comment by AAndersn** [comment]
Hello,

For application development, we recommend using the windows subsystem for linux. Complete instructions are available at 

https://github.com/GRIDAPPSD/gridappsd-hackathon/blob/main/Lesson%201.0.%20Installation%20Instructions.pdf

If you don't plan on using the API training notebooks, you can skip steps 1.4 through 1.7. 

Also, be sure to reach out for an invitation to the monthly app developers meeting.

**Comment by Lakes-lead** [comment]
Hello Alexander,

Thank you for response.

Does the OpenDSS simulator now works with the GridAppsD platform or just the Gridlabsd for now . 

Thank you 

Best regards,

**Comment by AAndersn** [comment]
Only GridLab-D currently. OpenDSS simulation will be added in a future release.

By the way, check out the new discussion board we created a few days ago. It is the perfect place to ask these type of questions and anything you need help / support / advice on.

https://github.com/GRIDAPPSD/gridappsd-forum/discussions
