### ISSUE TITLE
Document changing ip address in Viz on readthedocs 

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/gridappsd-forum#93]
Some external users are accessing Viz with remote IP address instead of localhost. If I remember correctly this needs a config file change in Viz container. Document the steps to change the config file on readthedocs so we can send that link to users.

**Comment by AAndersn** [comment]
https://gridappsd-training.readthedocs.io/en/develop/installation/1.7--Lesson-1.7--Cloud-Server-Configuration.html

**Comment by AAndersn** [comment]
@tonya1 or @bibiraju, please review and close

https://gridappsd-training.readthedocs.io/en/develop/installation/1.7-Cloud-Server-Configuration.html

**Comment by tonya1** [comment]
@AAndersn I think we also need to add the instructions for mounting the file into the container by updating the docker-compose.yml file.

**Comment by AAndersn** [comment]
Updated to use `-r` option for remote viz

https://gridappsd-training.readthedocs.io/en/develop/installation/1.7-Cloud-Server-Configuration.html
